### ISSUE TITLE
[frontend] 글로벌 헤더 모든 이슈

### ISSUE THREAD

**Issue by Eomhyunjun** [ft-nobrand/ft_transcendence#31]
- [x] 네비게이션 기능 #12 
- [x] 프로필 기능
- [x] 프로필 설정 기능
   - [x] 프로필 정보
   - [x] 친구 목록
   - [x] 프로필 설정
   - [x] Two-Factor-Auth
   - [x] 로그아웃
- [x] 백엔드와 데이터 통신
- [x] 전반적인 CSS

**Comment by Kyalivia** [comment]
* 글로벌 헤더에서 유저네임 옆에 로그아웃 버튼 추가
![스크린샷 2022-09-04 오후 6 05 53](https://user-images.githubusercontent.com/49050588/188306188-be28f592-ff95-48ba-868b-5545497e27a7.png)
* 프로필 설정 기능 -> 페이지 단위로 구현
  * 상태창(->정보창)
    * /profile/info
  * 친구목록
    * /profile/friends
  * 프로필 설정
    * /profile/setting
  * 이중 인증 설정
    * /profile/tfa
